name: Mobove
version: 1.0
main: mobi.MainMobi
api-version: 1.18

commands:
  _blabla:
  _vesnicanNaKoni:
  _zombieNaPavoukovi:
  _duhovaOvecka:
  _kocka:
  _liska:
  _obrPepa:
  _obrPepik:
  _enderDrak:
  _prikladyMobu:
  _vesnican:
  _hejnoSlepic:
  _rojVcel:
  _smeckaVlku:
  _stadoOvci: